services:
  postgres:
    container_name: sintonia-manager-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: sintonia_db
  # mailpit:
  #   image: 'axllent/mailpit:latest'
  #   ports:
  #     - 1025:1025
  #     - 8025:8025
